server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.97.180.232:3306/public?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: public
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true